# Generated by Django 6.0.2 on 2026-03-02 20:28

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                default="Ivan",
                max_length=50,
                validators=[users.validators.is_only_letters],
                verbose_name="Имя",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="patronymic",
            field=models.CharField(
                default="Иванов",
                max_length=50,
                validators=[users.validators.is_only_letters],
                verbose_name="Отчество",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="surname",
            field=models.CharField(
                default="Иванов",
                max_length=50,
                validators=[users.validators.is_only_letters],
                verbose_name="Фамилия",
            ),
            preserve_default=False,
        ),
    ]
