# Generated by Django 6.0.2 on 2026-03-02 20:31

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_name_customuser_patronymic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="surname",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                max_length=50,
                validators=[users.validators.is_only_letters],
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                max_length=50,
                validators=[users.validators.is_only_letters],
                verbose_name="Фамилия",
            ),
        ),
    ]
