# Generated by Django 6.0.2 on 2026-03-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_name_remove_customuser_surname_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["email"],
                "permissions": [
                    (
                        "can_change_users_work_position",
                        "Может изменять только должность пользователя",
                    ),
                    (
                        "can_change_users_department",
                        "Может изменять только подразделение пользователя",
                    ),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
