# Generated by Django 5.2.11 on 2026-03-02 13:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Название задачи"),
                ),
                (
                    "days_to_complete",
                    models.SmallIntegerField(
                        blank=True,
                        default=2,
                        null=True,
                        verbose_name="Кол-во дней для выполнения задания",
                    ),
                ),
                (
                    "date_to_complete",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            2026, 3, 4, 13, 14, 33, 388546, tzinfo=datetime.timezone.utc
                        ),
                        null=True,
                        verbose_name="Дата, до которой должна быть выполнена задача",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Запущена"),
                            ("stoped", "Завершена"),
                        ],
                        default="started",
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "task_description",
                    models.TextField(max_length=1500, verbose_name="Описание задания"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executor_task",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="task.task",
                        verbose_name="Наследуемая задача",
                    ),
                ),
                (
                    "task_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_manager",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Постановщик задачи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["-created_at"],
            },
        ),
    ]
