# Generated by Django 5.2.11 on 2026-03-02 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_to_complete",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2026, 3, 4, 19, 3, 6, 445264, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Дата, до которой должна быть выполнена задача",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("overdue", "Просрочена"),
                    ("stoped", "Завершена"),
                ],
                default="started",
                verbose_name="Статус задачи",
            ),
        ),
    ]
