# Generated by Django 6.0.2 on 2026-03-02 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_task_date_to_complete_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_to_complete",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2026, 3, 4, 20, 24, 53, 121941, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Дата, до которой должна быть выполнена задача",
            ),
        ),
    ]
