# Generated by Django 6.0.2 on 2026-03-02 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_alter_task_date_to_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_to_complete",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2026, 3, 4, 20, 48, 14, 534928, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Дата, до которой должна быть выполнена задача",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="days_to_complete",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Кол-во дней для выполнения задания"
            ),
        ),
    ]
