# Generated by Django 6.0.2 on 2026-03-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0006_alter_task_date_to_complete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_to_complete",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата, до которой должна быть выполнена задача",
            ),
        ),
    ]
