# Generated by Django 6.0.2 on 2026-03-03 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0008_alter_task_executor_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_task",
                to="task.task",
                verbose_name="Наследуемая задача",
            ),
        ),
    ]
