# Generated by Django 6.0.2 on 2026-03-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0009_alter_task_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "can_change_task_executor",
                        "Может изменять только исполнителя задачи",
                    ),
                    ("can_change_task_title", "Может изменять только название задачи"),
                    (
                        "can_change_task_description",
                        "Может изменять только описание задачи",
                    ),
                    ("can_change_task_dates", "Может изменять только даты задачи"),
                ],
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
