# Generated by Django 6.0.2 on 2026-03-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0010_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
